version: '3.7'
services:
  app:
    container_name: mutants-api
    image: mutants-api
    build: ./
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: dbpostgresql:5432
  dbpostgresql:
    container_name: mutants-postgresql
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=p0stgr3sql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mutantsdb